baseURL = "http://www.sarabatevik.com"
title = "Sara Båtevik"
theme = "hugo-coder"
languageCode = "en"
defaultContentLanguage = "en"
enableEmoji = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[pagination]
pagerSize = 6

[services]
[services.disqus]
# Enable Disqus comments
# shortname = "yourdiscussshortname"

[markup]
[markup.highlight]
noClasses = false

[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[params]
author = "Sara Båtevik"
# license = '<a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA-4.0</a>'
description = "Sara Båtevik's website"
keywords = "blog,developer,personal"
info = ["Electronics Systems Engineer"] #I can do ["Electronics Systems Engineer", "second"] 
avatarURL = "images/avatar.jpeg"
#gravatar = "john.doe@example.com"
dateFormat = "January 2, 2006"
since = 2025
# Git Commit in Footer, uncomment the line below to enable it
commit = "https://github.com/luizdepra/hugo-coder/tree/"
# Right To Left, shift content direction for languages such as Arabic
rtl = false
# Specify light/dark colorscheme
# Supported values:
# "auto" (use preference set by browser)
# "dark" (dark background, light foreground)
# "light" (light background, dark foreground) (default)
colorScheme = "dark"
# Hide the toggle button, along with the associated vertical divider
hideColorSchemeToggle = false
# Series see also post count
maxSeeAlsoItems = 5
# Custom CSS
customCSS = []
# Custom SCSS, file path is relative to Hugo's asset folder (default: {your project root}/assets)
customSCSS = []

# Custom JS
customJS = []

# Custom remote JS files
customRemoteJS = []

[[params.social]]
name = "Github"
icon = "fa-brands fa-github fa-2x"
weight = 1
url = "https://github.com/sassybuns/"

[[params.social]]
name = "Gitlab"
icon = "fa-brands fa-gitlab fa-2x"
weight = 2
url = "https://gitlab.com/sassybuns/"

#[[params.social]]
#name = "Twitter"
#icon = "fa-brands fa-x-twitter fa-2x"
#weight = 3
#url = "https://twitter.com/johndoe/"

[[params.social]]
name = "LinkedIn"
icon = "fa-brands fa-linkedin fa-2x"
weight = 4
url = "https://www.linkedin.com/in/sarabåtevik/"

#[[params.social]]
#name = "Medium"
#icon = "fa-brands fa-medium fa-2x"
#weight = 5
#url = "https://medium.com/@johndoe"

[[params.social]]
name = "RSS"
icon = "fa-solid fa-rss fa-2x"
weight = 6
url = "https://myhugosite.com/index.xml"
rel = "alternate"
type = "application/rss+xml"

[languages.en]
languageName = ":uk:"

[[languages.en.menu.main]]
name = "CV"
weight = 1
url = "cv/"

[[languages.en.menu.main]]
name = "Projects"
weight = 2
url = "projects/"

[[languages.en.menu.main]]
name = "About"
weight = 3
url = "about/"

#[languages.no]
#languageName = ":norway:"
#title = "Sara Båtevik"

#[languages.no.params]
#author = "Sara Båtevik"
#info = "Elektronisk Systemingeniør"
#description = "Sara Båtevik sin nettside"
#keywords = "blog, utvikler, personlig"

#[[languages.no.menu.main]]
#name = "CV"
#weight = 1
#url = "cv/"

#[[languages.no.menu.main]]
#name = "Prosjekter"
#weight = 2
#url = "prosjekter/"

#[[languages.no.menu.main]]
#name = "Kontakt"
#weight = 3
#url = "kontakt/"

#[[languages.no.menu.main]]
#name = "Om nettsiden"
#weight = 5
#url = "om-nettsiden/"
